import type { Cmd } from './types'

// ============ 共通线：回到临汐市的三十天 ============
export const scriptCommon: Cmd[] = [
  { t: 'label', name: 'start', chapter: '序章 · 潮声' },
  { t: 'bg', bg: 'black' },
  { t: 'bgm', track: null },
  { t: 'say', who: 'narrator', text: '临汐市，一座把海风吹进每一条街道的南方小城。' },
  { t: 'say', who: 'narrator', text: '离开的第十年，你回来了。不是旅行，是告别——外婆走了，留下海边那间旧咖啡馆。' },
  { t: 'say', who: 'narrator', text: '「蓝色尽头」。律师说，三十天后，它就会随着这片旧城区一起被拆除。' },
  { t: 'bg', bg: 'beach_dusk' },
  { t: 'bgm', track: 'title' },
  { t: 'say', who: 'narrator', text: '傍晚的海是橘子汽水的颜色。你拖着行李箱站在防波堤上，潮声一下一下，像很远的地方有人在敲一扇门。' },
  { t: 'say', who: 'player', text: '（十年了。这条街还是老样子，连咸腥味都没变。）' },
  { t: 'say', who: 'narrator', text: '咖啡馆比记忆里小了一圈。招牌褪成淡淡的蓝，门口的风铃缺了一根管子，风一过，响声就少了一个音。' },
  { t: 'jump', label: 'cafe_meet' },

  { t: 'label', name: 'cafe_meet', chapter: '第一章 · 蓝色尽头' },
  { t: 'bg', bg: 'cafe_day' },
  { t: 'bgm', track: 'daily' },
  { t: 'say', who: 'narrator', text: '推开门的瞬间，风铃残缺的响声惊动了吧台后的人。' },
  { t: 'show', char: 'wanqing', expr: 'surprise', pos: 'center' },
  { t: 'say', who: 'wanqing', text: '欢迎光——欸？' },
  { t: 'expr', char: 'wanqing', expr: 'neutral' },
  { t: 'say', who: 'wanqing', text: '……阿澈？真的是你？站在门口发什么呆，进来啊。' },
  { t: 'say', who: 'narrator', text: '苏晚晴。小时候总拽着你在礁石上疯跑的邻居姐姐，如今是这间咖啡馆的看板娘。' },
  { t: 'expr', char: 'wanqing', expr: 'smile' },
  { t: 'say', who: 'wanqing', text: '别愣着，坐。外婆走之前一直念叨，说你肯定会回来的。' },
  { t: 'say', who: 'player', text: '晚晴姐……这些年，一直是你在照看店？' },
  { t: 'expr', char: 'wanqing', expr: 'neutral' },
  { t: 'say', who: 'wanqing', text: '谈不上照看啦。你外婆教我烘豆子，我就赖着不走了。对了，你猜我现在另一份工作是什么？' },
  {
    t: 'choice',
    options: [
      { text: '「电台DJ？」', sub: '吧台上那台旧收音机，还贴着「3:03」的便签', jump: 'c1_dj' },
      { text: '「歌手？」', sub: '她哼歌的样子，好像确实有点专业', jump: 'c1_singer' },
    ],
  },

  { t: 'label', name: 'c1_dj' },
  { t: 'aff', char: 'wanqing', delta: 1 },
  { t: 'expr', char: 'wanqing', expr: 'smile' },
  { t: 'say', who: 'wanqing', text: '答对了！凌晨三点零三分，「星港电台」，全临汐最晚的一档节目。看来你还没把我忘干净嘛。' },
  { t: 'say', who: 'wanqing', text: '这台收音机就是我的「直播间」。老土吧？但外婆说，电波比网线诚实。' },
  { t: 'jump', label: 'c1_after' },

  { t: 'label', name: 'c1_singer' },
  { t: 'expr', char: 'wanqing', expr: 'angry' },
  { t: 'say', who: 'wanqing', text: '喂，我唱歌有那么难听吗？是DJ啦DJ！凌晨三点零三分，「星港电台」，你小时候明明听过的！' },
  { t: 'say', who: 'player', text: '（糟糕，她炸毛的样子倒是和十年前一模一样。）' },
  { t: 'jump', label: 'c1_after' },

  { t: 'label', name: 'c1_after' },
  { t: 'expr', char: 'wanqing', expr: 'neutral' },
  { t: 'say', who: 'wanqing', text: '……阿澈，店真的要拆吗？' },
  { t: 'say', who: 'player', text: '文件都签了。三十天。抱歉，晚晴姐。' },
  { t: 'expr', char: 'wanqing', expr: 'sad' },
  { t: 'say', who: 'wanqing', text: '道什么歉，又不是你的错。' },
  { t: 'expr', char: 'wanqing', expr: 'smile' },
  { t: 'say', who: 'wanqing', text: '行啦，今天先帮我干活！阁楼上有外婆留下的箱子，你上去翻翻。我请你喝本店最后的招牌——「蓝色尽头」。' },
  { t: 'hide', char: 'wanqing' },
  { t: 'say', who: 'narrator', text: '阁楼堆满了十年的灰尘。旧账本、发黄的照片、一摞摞手写的广播稿……外婆年轻时原来是海事电台的话务员。' },
  { t: 'say', who: 'narrator', text: '箱子最底下，有一枚印着帆船的木质杯垫，和一盘没有标签的录音带。' },
  {
    t: 'choice',
    options: [
      { text: '把杯垫收进口袋', sub: '【锚点 · 壹】帆影杯垫——外婆总用它垫那杯凉掉的手冲', jump: 'c1_coaster' },
      { text: '只带上录音带', sub: '标签被撕掉了，里面会是什么呢', jump: 'c1_tape_only' },
      { text: '都放回去吧', sub: '旧东西，就让它们留在旧地方', jump: 'c1_leave' },
    ],
  },

  { t: 'label', name: 'c1_coaster' },
  { t: 'flag', key: 'anchor_coaster' },
  { t: 'say', who: 'narrator', text: '【获得锚点 · 帆影杯垫】木头的边缘被磨得圆润，像被很多年的手温焐过。' },
  { t: 'say', who: 'player', text: '（录音带也一起带上吧。总觉得……不该把它们丢在这里。）' },
  { t: 'jump', label: 'night_radio' },

  { t: 'label', name: 'c1_tape_only' },
  { t: 'say', who: 'narrator', text: '你把录音带揣进口袋。杯垫孤零零地留在箱底，帆船的漆已经斑驳。' },
  { t: 'jump', label: 'night_radio' },

  { t: 'label', name: 'c1_leave' },
  { t: 'say', who: 'narrator', text: '你合上箱子。灰尘落回去的声音，轻得像一声叹息。' },
  { t: 'jump', label: 'night_radio' },

  // ===== 深夜电台 =====
  { t: 'label', name: 'night_radio', chapter: '第二章 · 凌晨三点零三分' },
  { t: 'bg', bg: 'cafe_night' },
  { t: 'bgm', track: 'night' },
  { t: 'say', who: 'narrator', text: '你在咖啡馆的阁楼上住下了。夜里睡不着，凌晨三点，楼下的旧收音机忽然自己亮了。' },
  { t: 'show', char: 'wanqing', expr: 'neutral', pos: 'center' },
  { t: 'say', who: 'wanqing', text: '「晚上好，这里是星港电台，凌晨三点零三分。今晚也睡不着的人，请把音量拧小一点，陪我待一会儿。」' },
  { t: 'say', who: 'narrator', text: '是晚晴的声音。白天的她像汽水，深夜电波里的她，却像一杯温过的牛奶。' },
  { t: 'say', who: 'wanqing', text: '「今天啊，店里回来了一个很久不见的人。他小时候怕黑，睡觉一定要开着收音机——喂，如果你在听，别笑。」' },
  { t: 'say', who: 'player', text: '（……被发现了。）' },
  { t: 'say', who: 'wanqing', text: '「这间店三十天后就要拆掉了。我没什么本事，拦不住推土机。但至少，我想把它的声音留下来。」' },
  { t: 'expr', char: 'wanqing', expr: 'smile' },
  { t: 'say', who: 'wanqing', text: '「所以今晚的点歌是——《海边的卡夫卡》。晚安，蓝色尽头。晚安，怕黑的小孩。」' },
  { t: 'hide', char: 'wanqing' },
  { t: 'say', who: 'narrator', text: '音乐响起的时候，你注意到收音机的指针微微颤动，停在一个不该存在的频段上——' },
  { t: 'say', who: 'narrator', text: 'FM 103.0。临汐市的电台表上，没有这个频率。' },
  { t: 'jump', label: 'rooftop' },

  // ===== 天台与星眠 =====
  { t: 'label', name: 'rooftop', chapter: '第三章 · 天台上的失眠者' },
  { t: 'bg', bg: 'rooftop_night' },
  { t: 'bgm', track: 'night' },
  { t: 'say', who: 'narrator', text: '第二天夜里，你爬上咖啡馆的天台检修那台老天线——收音机就是靠它收到 103.0 的。' },
  { t: 'say', who: 'narrator', text: '天台上却已经有人了。长发被夜风吹起来，膝上摊着一本写满公式的观测笔记。' },
  { t: 'show', char: 'xingmian', expr: 'neutral', pos: 'center' },
  { t: 'say', who: 'xingmian', text: '……你踩到我的星图了。退后三步，谢谢。' },
  { t: 'say', who: 'player', text: '这里是私人天台吧，你哪位？' },
  { t: 'say', who: 'xingmian', text: '沈星眠。市天文台的研究生。这间屋子的主人允许我在这里观测——租约签到了房子拆除那天。' },
  { t: 'expr', char: 'xingmian', expr: 'sad' },
  { t: 'say', who: 'xingmian', text: '也就是说，再过二十七天，我就要和我的猎户座一起搬家了。' },
  { t: 'say', who: 'narrator', text: '她的望远镜对着城市上空。霓虹把夜空染成紫色，星星却一颗一颗，倔强地亮着。' },
  { t: 'say', who: 'xingmian', text: '我的课题是「城市上空的电波尘埃」。这栋老楼的天线是个宝藏——它能收到别处的仪器收不到的东西。' },
  { t: 'expr', char: 'xingmian', expr: 'neutral' },
  { t: 'say', who: 'xingmian', text: '比如，一个不该存在的频段。FM 103.0。……你果然也听到了。' },
  {
    t: 'choice',
    options: [
      { text: '「我帮你调天线吧。」', sub: '【锚点 · 贰】让 103.0 更清楚一点', jump: 'c2_fix' },
      { text: '「那只是串台而已吧。」', sub: '别把自己搞得神神叨叨的', jump: 'c2_deny' },
    ],
  },

  { t: 'label', name: 'c2_fix' },
  { t: 'flag', key: 'anchor_antenna' },
  { t: 'aff', char: 'xingmian', delta: 1 },
  { t: 'expr', char: 'xingmian', expr: 'surprise' },
  { t: 'say', who: 'xingmian', text: '……你会修真空管？' },
  { t: 'say', who: 'player', text: '不会，但我拧螺丝的姿势很专业。' },
  { t: 'expr', char: 'xingmian', expr: 'smile' },
  { t: 'say', who: 'xingmian', text: '噗。……谢谢。你这个人，比看起来靠谱一点。' },
  { t: 'say', who: 'narrator', text: '【获得锚点 · 星轨天线】你们并肩拧紧了最后一个接口。夜风穿过天线，发出很轻的、像口哨一样的鸣响。' },
  { t: 'jump', label: 'c2_after' },

  { t: 'label', name: 'c2_deny' },
  { t: 'expr', char: 'xingmian', expr: 'angry' },
  { t: 'say', who: 'xingmian', text: '串台不会连续七天念同一串坐标。也不会……念出我去世导师的名字。' },
  { t: 'say', who: 'narrator', text: '她合上了笔记。你忽然意识到，这个冷静得像仪器的女孩，声音里有一道很细的裂缝。' },
  { t: 'jump', label: 'c2_after' },

  { t: 'label', name: 'c2_after' },
  { t: 'expr', char: 'xingmian', expr: 'neutral' },
  { t: 'say', who: 'xingmian', text: '阿澈，对吧。我有很严重的失眠症，睡不着的时候数星星，比数羊有用。' },
  { t: 'expr', char: 'xingmian', expr: 'smile' },
  { t: 'say', who: 'xingmian', text: '这台收音机借我录几个晚上，可以吗？作为交换——失眠的时候，我教你认星座。' },
  { t: 'hide', char: 'xingmian' },
  { t: 'say', who: 'narrator', text: '那一晚你们认完了整个夏季大三角。她睡着的时候，笔记摊开在「电波尘埃」那一页，眉头终于松开了。' },
  { t: 'jump', label: 'bailu_appear' },

  // ===== 白露出现 =====
  { t: 'label', name: 'bailu_appear', chapter: '第四章 · 频段彼端' },
  { t: 'bg', bg: 'radio_room' },
  { t: 'bgm', track: 'signal' },
  { t: 'say', who: 'narrator', text: '第三个凌晨，三点零三分，晚晴的节目结束后，收音机没有安静下来。' },
  { t: 'say', who: 'narrator', text: '白噪音像潮水一样涨起来，然后——一个声音从杂音里浮了出来。' },
  { t: 'show', char: 'bailu', expr: 'neutral', pos: 'center' },
  { t: 'say', who: 'bailu', text: '……沙沙……听得到吗？这里是——十年后的，同一天。' },
  { t: 'say', who: 'player', text: '你是谁？' },
  { t: 'expr', char: 'bailu', expr: 'smile' },
  { t: 'say', who: 'bailu', text: '白露。节气的那个白露。我是被这栋楼记住的声音，是还没有说完的话。' },
  { t: 'say', who: 'bailu', text: '信号衰减得很厉害……阿澈，时间不多了。房子拆掉那天，我也会跟着沉默。' },
  { t: 'expr', char: 'bailu', expr: 'sad' },
  { t: 'say', who: 'bailu', text: '想让我留下来，就去找三枚「锚点」——被认真记住的东西，会成为信号的岸。' },
  { t: 'say', who: 'player', text: '等等，你到底是谁？是……外婆吗？' },
  { t: 'say', who: 'bailu', text: '……沙沙……是，也不是。去找那盘录音带，听完它，你就知道了。' },
  { t: 'flag', key: 'met_bailu' },
  {
    t: 'choice',
    options: [
      { text: '「我会找到锚点的。」', sub: '不管你是谁，都不能就这样消失', jump: 'c3_promise' },
      { text: '「先证明你不是恶作剧。」', sub: '这年头，AI合成声音可太常见了', jump: 'c3_doubt' },
    ],
  },

  { t: 'label', name: 'c3_promise' },
  { t: 'aff', char: 'bailu', delta: 1 },
  { t: 'expr', char: 'bailu', expr: 'blush' },
  { t: 'say', who: 'bailu', text: '……嗯。这句话，和十年前的某个人说的一模一样。' },
  { t: 'say', who: 'bailu', text: '锚点可能是一件旧物、一次修好、一段被听完的录音……沙沙……记住，要「认真」。' },
  { t: 'jump', label: 'c3_after' },

  { t: 'label', name: 'c3_doubt' },
  { t: 'expr', char: 'bailu', expr: 'angry' },
  { t: 'say', who: 'bailu', text: '哼。那我说一件只有你知道的事——八岁那年，你在这间店的阁楼上，把外婆的航海日志弄丢了，哭了一整夜。' },
  { t: 'say', who: 'player', text: '（……！！这件事，我从来没有告诉过任何人。）' },
  { t: 'expr', char: 'bailu', expr: 'smile' },
  { t: 'say', who: 'bailu', text: '相信了吗？沙沙…… anchor，锚点，要用心找哦。' },
  { t: 'jump', label: 'c3_after' },

  { t: 'label', name: 'c3_after' },
  { t: 'hide', char: 'bailu' },
  { t: 'bgm', track: 'emotion' },
  { t: 'say', who: 'narrator', text: '信号沉入白噪音。你翻出那盘没有标签的录音带，放进阁楼的老录音机里。' },
  {
    t: 'choice',
    options: [
      { text: '从头听到尾', sub: '【锚点 · 叁】不管内容是什么，都认真听完', jump: 'c3_tape' },
      { text: '改天再说吧', sub: '今晚的信息量已经够大了', jump: 'c3_notape' },
    ],
  },

  { t: 'label', name: 'c3_tape' },
  { t: 'flag', key: 'anchor_tape' },
  { t: 'say', who: 'narrator', text: '磁带转动的沙沙声里，是年轻时的外婆。她在念一段海事电台的结束语——那是她职业生涯的最后一次播音。' },
  { t: 'say', who: 'narrator', text: '「……这里是临汐海事台。感谢各位三十年来的收听。海很大，但电波会记得每一个回家的人。晚安。」' },
  { t: 'say', who: 'narrator', text: '【获得锚点 · 最后的播音】磁带转完的时候，天蒙蒙亮。你的眼眶有一点热。' },
  { t: 'jump', label: 'festival_eve' },

  { t: 'label', name: 'c3_notape' },
  { t: 'say', who: 'narrator', text: '录音机安静地蹲在角落。你把磁带放回桌上，关灯躺下。窗外的潮声，听起来有点像谁在说话。' },
  { t: 'jump', label: 'festival_eve' },

  // ===== 烟火大会前夜 · 分歧 =====
  { t: 'label', name: 'festival_eve', chapter: '第五章 · 分歧点' },
  { t: 'bg', bg: 'street_neon' },
  { t: 'bgm', track: 'night' },
  { t: 'say', who: 'narrator', text: '日子像退潮一样过得飞快。距离拆除还有三天的时候，临汐市迎来了一年一度的海上烟火大会。' },
  { t: 'say', who: 'narrator', text: '这一晚，三个人几乎同时给你发来了消息。' },
  { t: 'say', who: 'narrator', text: '晚晴：「今晚来店里！我想办最后一场直播，缺一个打杂的，工资用汽水结算。」' },
  { t: 'say', who: 'narrator', text: '星眠：「今晚有英仙座流星雨极大值。天台，等你。……不来也行。」' },
  { t: 'say', who: 'narrator', text: '以及，收音机里沙沙作响的一句：「今晚的信号最强……来阁楼，我想把真相告诉你。」' },
  { t: 'say', who: 'narrator', text: '烟火在远处的海面上升起。你站在街口的霓虹灯下，做出选择。' },
  // 如果三线好感都不足，直接进入单人结局
  {
    t: 'dispatch',
    rules: [
      { label: 'route_choose', reqAff: { char: 'wanqing', min: 1 } },
      { label: 'route_choose', reqAff: { char: 'xingmian', min: 1 } },
      { label: 'route_choose', reqAff: { char: 'bailu', min: 1 } },
    ],
    fallback: 'solo_end',
  },

  { t: 'label', name: 'route_choose', chapter: '第五章 · 分歧点' },
  {
    t: 'choice',
    options: [
      { text: '去咖啡馆，帮晚晴办最后的直播', sub: '【苏晚晴线】汽水、麦克风与说不出口的话', jump: 'wq_route', reqAff: { char: 'wanqing', min: 1 } },
      { text: '去天台，陪星眠看流星雨', sub: '【沈星眠线】失眠者与猎户座的距离', jump: 'xm_route', reqAff: { char: 'xingmian', min: 1 } },
      { text: '去阁楼，听白露说出真相', sub: '【白露线】频段彼端的少女', jump: 'bl_route', reqAff: { char: 'bailu', min: 1 }, reqFlags: ['met_bailu'] },
    ],
  },
]
