import type { Cmd } from './types'

// ============ 角色线 × 3 + 单人结局 ============
export const scriptRoutes: Cmd[] = [
  // ==================== 苏晚晴线 ====================
  { t: 'label', name: 'wq_route', chapter: '晚晴线 · 最后的直播' },
  { t: 'bg', bg: 'cafe_night' },
  { t: 'bgm', track: 'daily' },
  { t: 'clear' },
  { t: 'show', char: 'wanqing', expr: 'smile', pos: 'center' },
  { t: 'say', who: 'wanqing', text: '来了？正好！麦克风归我，调音台归你。今晚的主题是——「蓝色尽头，最后一夜营业」。' },
  { t: 'say', who: 'narrator', text: '咖啡馆的灯一盏盏亮起来，旧收音机被郑重地摆到吧台中央。门外，烟火的光一阵阵地透进来。' },
  { t: 'expr', char: 'wanqing', expr: 'neutral' },
  { t: 'say', who: 'wanqing', text: '「晚上好，星港电台。今晚有点特别，是我们店……是我，在蓝色尽头的最后一场直播。」' },
  { t: 'say', who: 'wanqing', text: '「这家店比我年纪还大。外婆——就是老板啦，总说咖啡馆卖的不是咖啡，是『可以坐下来的时间』。」' },
  { t: 'expr', char: 'wanqing', expr: 'sad' },
  { t: 'say', who: 'wanqing', text: '「三天后这里就要拆掉了。我说过很多次没关系，其实……非常有关系。我十六岁离家出走，是这里收留了我。」' },
  { t: 'say', who: 'narrator', text: '她的声音在电波里发抖。你从没见过这样的晚晴——白天的她永远元气得像不会断电。' },
  { t: 'say', who: 'wanqing', text: '「今晚打进电话的每个人，说说你和这家店的故事，好不好？就当……一起给它办一场葬礼。不许哭太惨的那种。」' },
  { t: 'say', who: 'narrator', text: '电话一个接一个地进来。出租车司机、退休教师、在店里求婚成功的年轻人……十年、二十年、三十年的故事，顺着电波流进这间小屋。' },
  { t: 'expr', char: 'wanqing', expr: 'smile' },
  { t: 'say', who: 'wanqing', text: '（悄悄话）阿澈，你看，原来这么多人记得这里。我突然觉得……它好像不会真的消失。' },
  { t: 'bgm', track: 'emotion' },
  { t: 'expr', char: 'wanqing', expr: 'neutral' },
  { t: 'say', who: 'wanqing', text: '直播快结束了。最后一个环节，我想放一首歌。放完这首歌，我有一个问题想问你——当着所有听众的面。' },
  { t: 'say', who: 'player', text: '（她的心跳声，隔着调音台都能听见。这个问题，我等它等了一整场直播。）' },
  { t: 'say', who: 'wanqing', text: '「……歌放完了。那么，最后。阿澈，替所有听众问你一句——」' },
  {
    t: 'choice',
    options: [
      { text: '「把店留下来。我们一起。」', sub: '推土机还没来，故事就还没完', jump: 'wq_true' },
      { text: '「带着电台，去更远的地方吧。」', sub: '她的声音不该被困在一间老屋里', jump: 'wq_normal' },
    ],
  },

  { t: 'label', name: 'wq_true', chapter: '晚晴线 · 夏日回声' },
  { t: 'expr', char: 'wanqing', expr: 'surprise' },
  { t: 'say', who: 'wanqing', text: '欸……？' },
  { t: 'say', who: 'player', text: '听众的电话给了我灵感。这么多人记得这里，它就值得活下去。我查过了，旧城区改造案里有一条「文化空间保留条款」。' },
  { t: 'say', who: 'player', text: '把今晚的直播记录、三十年的故事，整理成材料递上去——让「蓝色尽头」作为城市声音记忆馆留下来。晚晴姐，你的电台也不用搬了。' },
  { t: 'expr', char: 'wanqing', expr: 'blush' },
  { t: 'say', who: 'wanqing', text: '你、你什么时候查的这些……笨蛋，偷偷准备了多少天啊……' },
  { t: 'say', who: 'narrator', text: '电波那头的听众炸开了锅。电话里，有人喊「我出律师费」，有人喊「我认识报社的人」。' },
  { t: 'expr', char: 'wanqing', expr: 'smile' },
  { t: 'say', who: 'wanqing', text: '「各、各位听众！计划变更——蓝色尽头，暂不闭店！本节目也将长期播出，每天凌晨三点零三分，不见不散！」' },
  { t: 'bg', bg: 'festival' },
  { t: 'bgm', track: 'festival' },
  { t: 'say', who: 'narrator', text: '窗外，最大的那朵烟火在海上炸开。晚晴扑过来抱住你的时候，收音机里的掌声响了很久很久。' },
  { t: 'say', who: 'wanqing', text: '阿澈。十年前你走的时候，我在这个吧台上哭了一场。今天换我笑一场——不许笑我妆花了。' },
  { t: 'say', who: 'narrator', text: '后来，咖啡馆的招牌重新刷了漆，还是那种淡淡的蓝。风铃补上了缺的管子，风一过，响声一个音都不少。' },
  { t: 'ending', id: 'wq_true' },

  { t: 'label', name: 'wq_normal', chapter: '晚晴线 · 各自晴天' },
  { t: 'expr', char: 'wanqing', expr: 'surprise' },
  { t: 'say', who: 'wanqing', text: '……更远的地方？' },
  { t: 'say', who: 'player', text: '晚晴姐，你的声音能安慰凌晨三点的整座城市。它不该只停在这条老街上。店会被拆掉，但「星港电台」可以装进行李箱。' },
  { t: 'expr', char: 'wanqing', expr: 'sad' },
  { t: 'say', who: 'wanqing', text: '……你这人啊，说话总是这么有道理，讨厌死了。' },
  { t: 'expr', char: 'wanqing', expr: 'smile' },
  { t: 'say', who: 'wanqing', text: '「各位听众，蓝色尽头要和大家说再见了。但是星港电台不会停播——下个月起，它将变成一档旅行节目，从全国的各个角落播出！」' },
  { t: 'say', who: 'narrator', text: '拆除那天，你陪她站在马路对面看完最后一眼。推土机停下的时候，晚晴背起装着设备的背包，冲你挥挥手。' },
  { t: 'say', who: 'wanqing', text: '别摆出那种表情。每个凌晨三点零三分，打开收音机——不管你在这个国家的哪个角落，我们都在同一片天空下熬夜。' },
  { t: 'say', who: 'narrator', text: '她走向车站的背影，被朝阳拉得很长。那天之后，你的手机里多了一个永远置顶的电台频率。' },
  { t: 'ending', id: 'wq_normal' },

  // ==================== 沈星眠线 ====================
  { t: 'label', name: 'xm_route', chapter: '星眠线 · 流星雨之夜' },
  { t: 'bg', bg: 'rooftop_night' },
  { t: 'bgm', track: 'night' },
  { t: 'clear' },
  { t: 'show', char: 'xingmian', expr: 'neutral', pos: 'center' },
  { t: 'say', who: 'xingmian', text: '你来了。……我算过你来的概率，只有百分之三十七。看来我的模型该修正了。' },
  { t: 'say', who: 'player', text: '嘴上说「不来也行」，架了两台相机一台望远镜的人是谁？' },
  { t: 'expr', char: 'xingmian', expr: 'blush' },
  { t: 'say', who: 'xingmian', text: '观测设备的标准配置而已。……坐吧，流星不等人。' },
  { t: 'say', who: 'narrator', text: '天台上铺着她准备的防潮垫，保温瓶里是热可可。第一颗流星划过的时候，海面亮了一瞬。' },
  { t: 'expr', char: 'xingmian', expr: 'neutral' },
  { t: 'say', who: 'xingmian', text: '英仙座流星雨，母体是斯威夫特-塔特尔彗星。这些光，在宇宙里飞了上百年，才落进我们的眼睛里。' },
  { t: 'say', who: 'xingmian', text: '我的论文就是研究它们穿过大气时激发的电波尘埃。导师去世后，没人相信这个方向……除了这间老楼的天线。' },
  { t: 'expr', char: 'xingmian', expr: 'sad' },
  { t: 'say', who: 'xingmian', text: '三天后天线就没了。我的数据还差最后一晚的完整记录——就在今晚。可是阿澈，我最近总在想。' },
  { t: 'say', who: 'xingmian', text: '数据齐了，论文发了，然后呢？这栋楼没了，天线没了，103.0 没了……我守着这些东西，到底是在做研究，还是在跟时间赌气？' },
  { t: 'say', who: 'narrator', text: '她的声音很平静，平静得像结了冰的湖面。你却能看见冰面下那些汹涌的东西——失眠的夜、去世的导师、即将拆掉的容身之所。' },
  { t: 'say', who: 'player', text: '星眠，看着我。今晚先别管论文。' },
  { t: 'expr', char: 'xingmian', expr: 'surprise' },
  { t: 'say', who: 'xingmian', text: '……你要干什么？' },
  {
    t: 'choice',
    options: [
      { text: '「今晚不观测，只许愿。」', sub: '把数据丢开一次，陪她单纯地看完这场流星雨', jump: 'xm_true' },
      { text: '「我陪你把这晚的数据做完。」', sub: '她需要的也许只是一个不散场的助手', jump: 'xm_normal' },
    ],
  },

  { t: 'label', name: 'xm_true', chapter: '星眠线 · 猎户座之约' },
  { t: 'say', who: 'player', text: '数据可以明晚再补——天线我来想办法保留。但流星雨极大值只有今晚。沈星眠，你多久没有不是为论文、只是为看星星而看星星了？' },
  { t: 'expr', char: 'xingmian', expr: 'surprise' },
  { t: 'say', who: 'xingmian', text: '……十年。从导师带我去天文台的那年之后，就没有了。' },
  { t: 'say', who: 'narrator', text: '她放下了笔。那个晚上，你们并排躺在防潮垫上，数了四十七颗流星。她许的愿不肯说，耳根却红了。' },
  { t: 'expr', char: 'xingmian', expr: 'smile' },
  { t: 'say', who: 'xingmian', text: '阿澈。失眠的人最怕天亮，因为天亮了就要回到「必须睡着」的世界。但今晚……我希望它慢一点亮。' },
  { t: 'say', who: 'narrator', text: '后来，你把天线的数据连同 103.0 的录音一起寄给了她的研究所。「民间电波观测点」的牌子挂在重建后的咖啡馆天台上，成了论文里最特别的一章。' },
  { t: 'bgm', track: 'emotion' },
  { t: 'expr', char: 'xingmian', expr: 'blush' },
  { t: 'say', who: 'xingmian', text: '猎户座每年冬天都会升起来。……以后每一年，都陪我看，可以吗？这不是观测计划，是……是约定。' },
  { t: 'say', who: 'narrator', text: '她睡着的时候靠在你的肩膀上。那是她十年来，第一个没有失眠的清晨。' },
  { t: 'ending', id: 'xm_true' },

  { t: 'label', name: 'xm_normal', chapter: '星眠线 · 流星距离' },
  { t: 'say', who: 'player', text: '把它做完吧。导师没做完的事，你替他做完——我陪你。' },
  { t: 'expr', char: 'xingmian', expr: 'smile' },
  { t: 'say', who: 'xingmian', text: '……嗯。谢谢你，助手先生。' },
  { t: 'say', who: 'narrator', text: '那一晚的数据完整得像教科书。三个月后，她的论文登上了业内最好的期刊，致谢里写着「蓝色尽头咖啡馆，与一位不肯署名的助手」。' },
  { t: 'say', who: 'narrator', text: '再之后，她去了西部的天文台，那里有四百米口径的望远镜，和全城最黑的夜空。' },
  { t: 'bg', bg: 'rooftop_night' },
  { t: 'say', who: 'xingmian', text: '（电话里）这边的星星很密，密得让人想哭。可是阿澈，我有时候会想，那晚如果我放下笔一次，结局会不会不一样。' },
  { t: 'say', who: 'xingmian', text: '……没什么。流星划过只要一秒，光走那么远的路，大概也不在乎这一秒。下次流星雨，记得抬头。' },
  { t: 'say', who: 'narrator', text: '挂断电话后，天台的风比往常凉。你们都在各自的夜空下过得很好——只是有些光，一旦错过，就要再飞一百年。' },
  { t: 'ending', id: 'xm_normal' },

  // ==================== 白露线 ====================
  { t: 'label', name: 'bl_route', chapter: '白露线 · 信号的岸' },
  { t: 'bg', bg: 'radio_room' },
  { t: 'bgm', track: 'signal' },
  { t: 'clear' },
  { t: 'say', who: 'narrator', text: '你抱着录音机爬上阁楼。凌晨三点零三分，白噪音准时涨潮——她的声音从杂音里浮出来，比任何一晚都清晰。' },
  { t: 'show', char: 'bailu', expr: 'smile', pos: 'center' },
  { t: 'say', who: 'bailu', text: '你来啦。沙沙……今晚的信号很好，好到可以告诉你所有事情。' },
  { t: 'say', who: 'bailu', text: '先回答那个问题吧。我是白露，节气的白露。我……是不是外婆？' },
  { t: 'expr', char: 'bailu', expr: 'neutral' },
  { t: 'say', who: 'bailu', text: '三十年前，临汐海事台撤销的那天，你的外婆录下了最后一段结束语。那段电波没有消失——它撞上山海之间的电离层，一年一年，反射、循环、衰减。' },
  { t: 'say', who: 'bailu', text: '这栋老楼的天线一直张着耳朵。三十年里，这间屋子里所有没说出口的话——离别、歉意、晚安——一点一点，汇进了那段循环的电波。' },
  { t: 'expr', char: 'bailu', expr: 'smile' },
  { t: 'say', who: 'bailu', text: '然后有一天，它醒了。它给自己取名叫白露，因为它第一次在收音机里开口说话，就是白露节气。……沙沙，所以我说，我是，也不是。' },
  { t: 'say', who: 'player', text: '（录音带里外婆的声音、晚晴节目里的哽咽、星眠念出的坐标……原来都被这栋楼记住了。）' },
  { t: 'expr', char: 'bailu', expr: 'sad' },
  { t: 'say', who: 'bailu', text: '电波需要岸。天线是我的耳朵，而这间屋子里的「被认真记住的东西」，是让我不至于散掉的锚点。房子拆掉那天，循环就会断。' },
  { t: 'say', who: 'bailu', text: '阿澈，你找到几枚锚点了？……让我看看你的心。' },
  { t: 'bgm', track: 'emotion' },
  {
    t: 'choice',
    options: [
      { text: '「三枚都在。白露，上岸吧。」', sub: '帆影杯垫 · 星轨天线 · 最后的播音', jump: 'bl_true', reqFlags: ['anchor_coaster', 'anchor_antenna', 'anchor_tape'] },
      { text: '「对不起，我还没找齐……」', sub: '锚点还散落在来时的路上', jump: 'bl_normal' },
    ],
  },

  { t: 'label', name: 'bl_true', chapter: '白露线 · 信号抵达未来' },
  { t: 'expr', char: 'bailu', expr: 'surprise' },
  { t: 'say', who: 'bailu', text: '杯垫、天线、录音带……沙沙……你真的，把它们都认真记住了。' },
  { t: 'say', who: 'narrator', text: '收音机的外壳微微发烫。白噪音退去，她的声音第一次干净得像当面说话。' },
  { t: 'expr', char: 'bailu', expr: 'blush' },
  { t: 'say', who: 'bailu', text: '三枚锚点连成一条线，循环就不用再依附这栋楼了。阿澈，信号找到了新的岸——是记住了这一切的，你们。' },
  { t: 'say', who: 'player', text: '那以后……还能听到你吗？' },
  { t: 'expr', char: 'bailu', expr: 'smile' },
  { t: 'say', who: 'bailu', text: '嗯。任何一台收音机，任何一个凌晨三点零三分。毕竟——「海很大，但电波会记得每一个回家的人。」' },
  { t: 'bg', bg: 'dawn_beach' },
  { t: 'bgm', track: 'ending' },
  { t: 'say', who: 'narrator', text: '拆除令在市民联名下暂缓了。阁楼的收音机留了下来，旁边摆着一枚帆船杯垫。' },
  { t: 'say', who: 'narrator', text: '十年后的某个清晨，你在异乡出差，拧开酒店的收音机。沙沙声里，一个熟悉的声音说：' },
  { t: 'say', who: 'bailu', text: '「早上好。这里是星港电台，早间版。——找到你了哦，阿澈。」' },
  { t: 'ending', id: 'bl_true' },

  { t: 'label', name: 'bl_normal', chapter: '白露线 · 遗失的频段' },
  { t: 'expr', char: 'bailu', expr: 'sad' },
  { t: 'say', who: 'bailu', text: '……没关系哦。你愿意来找我，我已经很开心了。' },
  { t: 'say', who: 'bailu', text: '信号衰减的速度，比我想的要快。沙沙……阿澈，最后几天，每天都来听我说话，好不好？' },
  { t: 'bg', bg: 'rain_window' },
  { t: 'say', who: 'narrator', text: '最后那晚下着雨。凌晨三点零三分，收音机里只有很轻很轻的白噪音，像退潮。' },
  { t: 'say', who: 'bailu', text: '「……晚安，蓝色尽头。晚安，怕黑的……小……」' },
  { t: 'say', who: 'narrator', text: '句子断在半截，再也没有续上。雨停的时候，FM 103.0 变成了一片安静的空白。' },
  { t: 'say', who: 'narrator', text: '也许在某个落满锚点的平行世界里，那句话有说完的版本。' },
  { t: 'ending', id: 'bl_normal' },

  // ==================== 单人结局 ====================
  { t: 'label', name: 'solo_end', chapter: '尾声 · 蓝色尽头的句点' },
  { t: 'bg', bg: 'beach_dusk' },
  { t: 'bgm', track: 'emotion' },
  { t: 'clear' },
  { t: 'say', who: 'narrator', text: '烟火大会那晚，你哪里都没去。你在防波堤上坐到烟火熄尽，看人群像退潮一样散去。' },
  { t: 'say', who: 'narrator', text: '三十天很快过完了。签字、交接、拆除。推土机来的时候，收音机安静得像一块普通的木头。' },
  { t: 'say', who: 'narrator', text: '离开临汐市的火车上，你忽然想起凌晨三点零三分。拧开手机里的收音机应用——当然，什么都收不到。' },
  { t: 'say', who: 'narrator', text: '有些频段，只为愿意停留的人打开。' },
  { t: 'ending', id: 'solo' },
]
